name: MDL Benchmark

on:
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "LICENSES/**"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "README.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "LICENSES/**"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "README.md"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [Windows, self-hosted]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: "0"
      - name: Common setup
        uses: ./.github/actions/common-setup
        with:
          os: windows
          compiler: cl
          platform: x86_64
          config: release
          build-llvm: true
      - name: Build Slang
        run: |
          echo "Skip"
      - uses: actions/checkout@v4
        with:
          repository: "shader-slang/MDL-SDK"
          path: "external/MDL-SDK"
          sparse-checkout: |
            ./examples/mdl_sdk/dxr/content/slangified
      - name: Run benchmark
        run: |
          echo "Skip"
