name: Test Slang

on:
  workflow_run:
    workflows: ["Build Slang"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        os: [linux, macos, windows]
        config: [debug, release]
        compiler: [gcc, clang, cl]
        platform: [x86_64, aarch64]
        exclude:
          # Default to x64, but aarch64 on osx
          - { os: linux, platform: aarch64 }
          - { os: windows, platform: aarch64 }
          - { os: macos, platform: x86_64 }
          # Unused compiler configs
          - { os: linux, compiler: clang }
          - { os: linux, compiler: cl }
          - { os: windows, compiler: gcc }
          - { os: windows, compiler: clang }
          - { os: macos, compiler: gcc }
          - { os: macos, compiler: cl }
        include:
          - { os: linux, runs-on: ubuntu-20.04 }
          - { os: macos, runs-on: macos-latest }
          - { os: windows, runs-on: windows-latest }
          - os: windows
            config: release
            runs-on: [Windows, self-hosted]
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: '0'
      
      - name: Download Slang executables
        uses: actions/download-artifact@v4
        with:
          name: test-slang-${{matrix.os}}-${{matrix.platform}}-${{matrix.compiler}}-${{matrix.config}}
          path: |
            build/*/bin
            build/test-slang.sh
            build/test-slang-via-glsl.sh
      
      - name: Test Slang
        run: |
          . build/test-slang.sh

      - name: Test Slang via GLSL
        run: |
          . build/test-slang-via-glsl.sh

